[target.riscv32imac-unknown-none-elf]
runner = "espflash flash --monitor"

[env]
ESP_LOG="INFO"

ESP_HAL_EMBASSY_CONFIG_TIMER_QUEUE="multiple-integrated"

ESP_WIFI_CONFIG_COUNTRY_CODE="DE"
ESP_WIFI_CONFIG_TX_QUEUE_SIZE="8"
ESP_WIFI_CONFIG_STATIC_TX_BUF_NUM="10"


[build]
rustflags = [
  # Required to obtain backtraces (e.g. when using the "esp-backtrace" crate.)
  # NOTE: May negatively impact performance of produced code
  "-C", "force-frame-pointers",
]

target = "riscv32imac-unknown-none-elf"

[unstable]
build-std = ["alloc", "core"]
build-std-features = ["panic_immediate_abort"]

